
export interface Category {
  id: string;
  title: string;
  description: string;
  icon: string;
  collection: 'Old Testament' | 'New Testament';
}

export interface QuizType {
  id: string;
  title: string;
  description: string;
}

export interface Question {
  id: string;
  collection: 'Old Testament' | 'New Testament';
  book: string;
  chapter: number;
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
  type: 'multiple-choice' | 'true-false' | 'fill-blank';
  question: string;
  choices: string[];
  answer: string;
  verse: string;
  explanation: string;
}

export const CATEGORIES: Category[] = [
  // Special Categories
  { id: 'messiahs-path', title: 'The Messiah’s Path', description: 'Follow the life of Jesus through the Gospel of Matthew in this epic journey.', icon: 'Map', collection: 'New Testament' },
  // Old Testament Books
  { id: 'genesis', title: 'Genesis', description: 'Creation, Fall, Flood, Patriarchs, and Covenants.', icon: 'Sparkles', collection: 'Old Testament' },
  { id: 'exodus', title: 'Exodus', description: 'Moses, Plagues, Passover, and the Law at Sinai.', icon: 'Scroll', collection: 'Old Testament' },
  { id: 'leviticus', title: 'Leviticus', description: 'Sacrifices, Priesthood, and Holiness Code.', icon: 'Flame', collection: 'Old Testament' },
  { id: 'numbers', title: 'Numbers', description: 'Wilderness wanderings and rebellion.', icon: 'Map', collection: 'Old Testament' },
  { id: 'deuteronomy', title: 'Deuteronomy', description: 'Covenant renewal and law repetition.', icon: 'BookOpen', collection: 'Old Testament' },
  { id: 'joshua', title: 'Joshua', description: 'Conquest of Canaan and land allotment.', icon: 'Sword', collection: 'Old Testament' },
  { id: 'judges', title: 'Judges', description: 'Cycles of apostasy and the judges.', icon: 'Scale', collection: 'Old Testament' },
  { id: 'ruth', title: 'Ruth', description: 'Loyalty, redemption, and God\'s providence.', icon: 'Heart', collection: 'Old Testament' },
  { id: '1-samuel', title: '1 Samuel', description: 'Samuel, Saul, and David\'s anointing.', icon: 'Crown', collection: 'Old Testament' },
  { id: '2-samuel', title: '2 Samuel', description: 'David\'s kingship and covenant.', icon: 'Crown', collection: 'Old Testament' },
  { id: '1-kings', title: '1 Kings', description: 'Solomon\'s reign and kingdom division.', icon: 'Building', collection: 'Old Testament' },
  { id: '2-kings', title: '2 Kings', description: 'Northern and Southern kingdoms, exile.', icon: 'Building', collection: 'Old Testament' },
  { id: 'psalms', title: 'Psalms', description: 'Praise, lament, and messianic prophecy.', icon: 'Music', collection: 'Old Testament' },
  { id: 'proverbs', title: 'Proverbs', description: 'Wisdom principles for righteous living.', icon: 'Feather', collection: 'Old Testament' },
  { id: 'isaiah', title: 'Isaiah', description: 'Judgment and messianic prophecy.', icon: 'Megaphone', collection: 'Old Testament' },
  { id: 'jeremiah', title: 'Jeremiah', description: 'Warnings and the new covenant.', icon: 'Megaphone', collection: 'Old Testament' },
  { id: 'ezekiel', title: 'Ezekiel', description: 'Visions of God and restoration.', icon: 'Eye', collection: 'Old Testament' },
  { id: 'daniel', title: 'Daniel', description: 'Faithfulness in exile and apocalyptic visions.', icon: 'Shield', collection: 'Old Testament' },
  // New Testament Books
  { id: 'matthew', title: 'Matthew', description: 'Life, teachings, and resurrection of Jesus.', icon: 'Star', collection: 'New Testament' },
  { id: 'mark', title: 'Mark', description: 'The servant Messiah and miracles.', icon: 'Zap', collection: 'New Testament' },
  { id: 'luke', title: 'Luke', description: 'Compassion of Jesus and parables.', icon: 'Heart', collection: 'New Testament' },
  { id: 'john', title: 'John', description: 'Signs, I Am statements, and eternal life.', icon: 'Sun', collection: 'New Testament' },
  { id: 'acts', title: 'Acts', description: 'Early church, Holy Spirit, and missions.', icon: 'Flame', collection: 'New Testament' },
  { id: 'romans', title: 'Romans', description: 'Sin, salvation, and justification by faith.', icon: 'Mail', collection: 'New Testament' },
  { id: '1-corinthians', title: '1 Corinthians', description: 'Church problems, love, and resurrection.', icon: 'Mail', collection: 'New Testament' },
  { id: 'galatians', title: 'Galatians', description: 'Freedom in Christ and law vs grace.', icon: 'Mail', collection: 'New Testament' },
  { id: 'ephesians', title: 'Ephesians', description: 'Unity in Christ and church identity.', icon: 'Mail', collection: 'New Testament' },
  { id: 'hebrews', title: 'Hebrews', description: 'Supremacy of Christ and new covenant.', icon: 'BookOpen', collection: 'New Testament' },
  { id: 'james', title: 'James', description: 'Practical faith and wisdom.', icon: 'Hammer', collection: 'New Testament' },
  { id: 'revelation', title: 'Revelation', description: 'Letters to churches, judgment, and new creation.', icon: 'Eye', collection: 'New Testament' }
];

export const QUIZ_TYPES: QuizType[] = [
  { id: 'standard', title: 'Standard Quiz', description: 'Mix of multiple choice questions.' },
  { id: 'verse', title: 'Finish the Verse', description: 'Complete the missing words.' },
  { id: 'who-said', title: 'Who Said It?', description: 'Identify the speaker.' },
];

export const QUESTIONS: Question[] = [
  // Genesis
  {
    id: 'gen_001_01',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 1,
    category: 'Creation',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'On which day did God create light?',
    choices: ['Day 1', 'Day 2', 'Day 3', 'Day 4'],
    answer: 'Day 1',
    verse: 'Genesis 1:3',
    explanation: 'God created light on the first day by His spoken command.'
  },
  {
    id: 'gen_001_02',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 1,
    category: 'Creation',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What did God create on the fourth day?',
    choices: ['Animals', 'Land', 'Sun, moon, and stars', 'Birds'],
    answer: 'Sun, moon, and stars',
    verse: 'Genesis 1:14-19',
    explanation: 'The heavenly lights were created to mark seasons and days.'
  },
  {
    id: 'gen_002_01',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 2,
    category: 'Creation',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'From what did God form the man?',
    choices: ['Water', 'Dust of the ground', 'Clay', 'Stone'],
    answer: 'Dust of the ground',
    verse: 'Genesis 2:7',
    explanation: 'God formed man from the dust and breathed life into him.'
  },
  {
    id: 'gen_003_01',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 3,
    category: 'Fall',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Which tree were Adam and Eve forbidden to eat from?',
    choices: ['Tree of Life', 'Tree of Knowledge of Good and Evil', 'Olive Tree', 'Fig Tree'],
    answer: 'Tree of Knowledge of Good and Evil',
    verse: 'Genesis 2:17',
    explanation: 'God commanded them not to eat from this tree.'
  },
  {
    id: 'gen_006_01',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 6,
    category: 'Flood',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Why did God decide to send the flood?',
    choices: ['Overpopulation', 'Human wickedness', 'Lack of faith', 'Idolatry only'],
    answer: 'Human wickedness',
    verse: 'Genesis 6:5',
    explanation: 'God saw that human evil had become widespread on the earth.'
  },
  {
    id: 'gen_009_01',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 9,
    category: 'Covenants',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What sign did God give as a covenant with Noah?',
    choices: ['A star', 'A rainbow', 'Fire', 'An altar'],
    answer: 'A rainbow',
    verse: 'Genesis 9:13',
    explanation: 'The rainbow was a sign of God\'s promise.'
  },
  {
    id: 'gen_012_01',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 12,
    category: 'Patriarchs',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who did God call to leave his country and go to a land He would show him?',
    choices: ['Noah', 'Abraham', 'Isaac', 'Jacob'],
    answer: 'Abraham',
    verse: 'Genesis 12:1',
    explanation: 'God called Abraham to leave Ur and go to Canaan.'
  },
  {
    id: 'gen_022_01',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 22,
    category: 'Patriarchs',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What did God ask Abraham to sacrifice?',
    choices: ['A lamb', 'His son Isaac', 'A bull', 'His possessions'],
    answer: 'His son Isaac',
    verse: 'Genesis 22:2',
    explanation: 'God tested Abraham by asking him to sacrifice his son Isaac.'
  },
  {
    id: 'gen_037_01',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 37,
    category: 'Joseph Narrative',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What item did Jacob give Joseph that caused jealousy?',
    choices: ['A ring', 'A staff', 'A special coat', 'Sandals'],
    answer: 'A special coat',
    verse: 'Genesis 37:3',
    explanation: 'The coat symbolized Jacob\'s favor toward Joseph.'
  },
  {
    id: 'gen_037_02',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 37,
    category: 'Joseph Narrative',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who was sold into slavery by his brothers?',
    choices: ['Jacob', 'Isaac', 'Joseph', 'Benjamin'],
    answer: 'Joseph',
    verse: 'Genesis 37:28',
    explanation: 'Joseph was sold by his jealous brothers to merchants going to Egypt.'
  },
  // Exodus
  {
    id: 'exo_003_01',
    collection: 'Old Testament',
    book: 'Exodus',
    chapter: 3,
    category: 'Moses',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Where did God speak to Moses from the burning bush?',
    choices: ['Mount Sinai', 'Mount Horeb', 'Mount Nebo', 'Mount Carmel'],
    answer: 'Mount Horeb',
    verse: 'Exodus 3:1-2',
    explanation: 'God appeared to Moses while he tended sheep.'
  },
  {
    id: 'exo_004_01',
    collection: 'Old Testament',
    book: 'Exodus',
    chapter: 4,
    category: 'Moses',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who was the brother of Moses chosen to be the High Priest?',
    choices: ['Joshua', 'Caleb', 'Aaron', 'Hur'],
    answer: 'Aaron',
    verse: 'Exodus 4:14',
    explanation: 'Aaron was chosen by God to speak for Moses and later served as the first High Priest.'
  },
  {
    id: 'exo_007_01',
    collection: 'Old Testament',
    book: 'Exodus',
    chapter: 7,
    category: 'Plagues',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What was the first plague in Egypt?',
    choices: ['Frogs', 'Blood', 'Locusts', 'Darkness'],
    answer: 'Blood',
    verse: 'Exodus 7:20',
    explanation: 'The Nile was turned into blood.'
  },
  {
    id: 'exo_007_02',
    collection: 'Old Testament',
    book: 'Exodus',
    chapter: 7,
    category: 'Plagues',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'How many plagues did God send upon Egypt?',
    choices: ['7', '10', '12', '5'],
    answer: '10',
    verse: 'Exodus 7-12',
    explanation: 'God sent 10 plagues upon Egypt before Pharaoh let the Israelites go.'
  },
  {
    id: 'exo_012_01',
    collection: 'Old Testament',
    book: 'Exodus',
    chapter: 12,
    category: 'Passover',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What was the final plague on Egypt?',
    choices: ['Locusts', 'Darkness', 'Death of the firstborn', 'Boils'],
    answer: 'Death of the firstborn',
    verse: 'Exodus 12:29',
    explanation: 'The death of the firstborn was the tenth and final plague that freed the Israelites.'
  },
  {
    id: 'exo_014_01',
    collection: 'Old Testament',
    book: 'Exodus',
    chapter: 14,
    category: 'Red Sea',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'How did Israel cross the Red Sea?',
    choices: ['By boat', 'On dry ground', 'By bridge', 'Swimming'],
    answer: 'On dry ground',
    verse: 'Exodus 14:22',
    explanation: 'God parted the waters so Israel crossed safely.'
  },
  {
    id: 'exo_032_01',
    collection: 'Old Testament',
    book: 'Exodus',
    chapter: 32,
    category: 'Law at Sinai',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What did the Israelites build while Moses was on Mount Sinai?',
    choices: ['A temple', 'A golden calf', 'An altar', 'A tower'],
    answer: 'A golden calf',
    verse: 'Exodus 32:4',
    explanation: 'While Moses was receiving the law, the people made a golden calf to worship.'
  },
  // Leviticus
  {
    id: 'lev_019_01',
    collection: 'Old Testament',
    book: 'Leviticus',
    chapter: 19,
    category: 'Holiness Code',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Why were the Israelites commanded to be holy?',
    choices: ['Because of the law', 'Because God is holy', 'To impress nations', 'To gain blessings'],
    answer: 'Because God is holy',
    verse: 'Leviticus 19:2',
    explanation: 'God\'s holiness sets the standard.'
  },
  // Numbers
  {
    id: 'num_014_01',
    collection: 'Old Testament',
    book: 'Numbers',
    chapter: 14,
    category: 'Rebellion',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Why did Israel wander in the wilderness for forty years?',
    choices: ['Lack of supplies', 'Disobedience', 'Poor leadership', 'War'],
    answer: 'Disobedience',
    verse: 'Numbers 14:33-34',
    explanation: 'Israel refused to trust God.'
  },
  // Deuteronomy
  {
    id: 'deu_006_01',
    collection: 'Old Testament',
    book: 'Deuteronomy',
    chapter: 6,
    category: 'Covenant Renewal',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What statement is known as the Shema?',
    choices: ['Keep the Sabbath', 'The Lord is one', 'Honor your parents', 'Love your neighbor'],
    answer: 'The Lord is one',
    verse: 'Deuteronomy 6:4',
    explanation: 'The Shema affirms Israel\'s devotion to God.'
  },
  // Joshua
  {
    id: 'jos_006_01',
    collection: 'Old Testament',
    book: 'Joshua',
    chapter: 6,
    category: 'Battles',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Which city\'s walls fell after Israel marched around them?',
    choices: ['Ai', 'Jericho', 'Hebron', 'Bethel'],
    answer: 'Jericho',
    verse: 'Joshua 6:20',
    explanation: 'God gave Israel victory at Jericho.'
  },
  {
    id: 'jos_006_02',
    collection: 'Old Testament',
    book: 'Joshua',
    chapter: 6,
    category: 'Conquest of Canaan',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who led the Israelites around the walls of Jericho?',
    choices: ['Moses', 'Joshua', 'Caleb', 'Gideon'],
    answer: 'Joshua',
    verse: 'Joshua 6',
    explanation: 'Joshua led the people in the conquest of Jericho.'
  },
  // Judges
  {
    id: 'jud_006_01',
    collection: 'Old Testament',
    book: 'Judges',
    chapter: 6,
    category: 'Major Judges',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Which judge defeated the Midianites with 300 men?',
    choices: ['Samson', 'Gideon', 'Deborah', 'Ehud'],
    answer: 'Gideon',
    verse: 'Judges 7:7',
    explanation: 'God reduced Gideon\'s army to 300 men to show His power in defeating Midian.'
  },
  {
    id: 'jud_004_01',
    collection: 'Old Testament',
    book: 'Judges',
    chapter: 4,
    category: 'Major Judges',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Which woman was a judge of Israel?',
    choices: ['Ruth', 'Deborah', 'Esther', 'Rahab'],
    answer: 'Deborah',
    verse: 'Judges 4:4',
    explanation: 'Deborah was a prophetess and the only female judge mentioned in the Bible.'
  },
  {
    id: 'jud_016_01',
    collection: 'Old Testament',
    book: 'Judges',
    chapter: 16,
    category: 'Major Judges',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What was the source of Samson\'s strength?',
    choices: ['His muscles', 'His hair', 'His faith', 'A special diet'],
    answer: 'His hair',
    verse: 'Judges 16:17',
    explanation: 'Samson\'s strength was tied to his Nazirite vow, symbolized by his uncut hair.'
  },
  // Ruth
  {
    id: 'rut_001_01',
    collection: 'Old Testament',
    book: 'Ruth',
    chapter: 1,
    category: 'Loyalty',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who said, "Where you go I will go"?',
    choices: ['Naomi', 'Ruth', 'Orpah', 'Boaz'],
    answer: 'Ruth',
    verse: 'Ruth 1:16',
    explanation: 'Ruth showed loyalty to Naomi.'
  },
  // 1 Samuel
  {
    id: '1sa_017_01',
    collection: 'Old Testament',
    book: '1 Samuel',
    chapter: 17,
    category: 'David\'s Anointing',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who did David defeat with a sling?',
    choices: ['Saul', 'Goliath', 'Jonathan', 'Abner'],
    answer: 'Goliath',
    verse: '1 Samuel 17:49',
    explanation: 'David trusted God for victory.'
  },
  // 2 Samuel
  {
    id: '2sa_007_01',
    collection: 'Old Testament',
    book: '2 Samuel',
    chapter: 7,
    category: 'Covenant with David',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What did God promise David?',
    choices: ['Riches', 'Peace', 'An everlasting kingdom', 'Long life'],
    answer: 'An everlasting kingdom',
    verse: '2 Samuel 7:16',
    explanation: 'God promised David\'s dynasty would endure.'
  },
  // 1 Kings
  {
    id: '1ki_003_01',
    collection: 'Old Testament',
    book: '1 Kings',
    chapter: 3,
    category: 'Solomon\'s Reign',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who was the wisest king of Israel?',
    choices: ['David', 'Solomon', 'Saul', 'Hezekiah'],
    answer: 'Solomon',
    verse: '1 Kings 3:12',
    explanation: 'Solomon asked God for wisdom and became the wisest king ever.'
  },
  {
    id: '1ki_006_01',
    collection: 'Old Testament',
    book: '1 Kings',
    chapter: 6,
    category: 'Temple Construction',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What did Solomon build for the Lord?',
    choices: ['A palace', 'The Temple', 'A city', 'An ark'],
    answer: 'The Temple',
    verse: '1 Kings 6:1',
    explanation: 'Solomon built the first Temple in Jerusalem for the Lord.'
  },
  // 2 Kings
  {
    id: '2ki_002_01',
    collection: 'Old Testament',
    book: '2 Kings',
    chapter: 2,
    category: 'Prophetic Ministry',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Which prophet was taken to heaven in a chariot of fire?',
    choices: ['Elisha', 'Elijah', 'Isaiah', 'Enoch'],
    answer: 'Elijah',
    verse: '2 Kings 2:11',
    explanation: 'Elijah was taken up to heaven in a whirlwind with a chariot of fire.'
  },
  // Ezra/Nehemiah
  {
    id: 'neh_002_01',
    collection: 'Old Testament',
    book: 'Nehemiah',
    chapter: 2,
    category: 'Wall Rebuilding',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who led the rebuilding of Jerusalem\'s walls?',
    choices: ['Ezra', 'Nehemiah', 'Zerubbabel', 'Haggai'],
    answer: 'Nehemiah',
    verse: 'Nehemiah 2:17',
    explanation: 'Nehemiah led the effort to rebuild Jerusalem\'s walls after the exile.'
  },
  // Esther
  {
    id: 'est_007_01',
    collection: 'Old Testament',
    book: 'Esther',
    chapter: 7,
    category: 'Deliverance',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Which queen saved her people from destruction?',
    choices: ['Jezebel', 'Esther', 'Bathsheba', 'Vashti'],
    answer: 'Esther',
    verse: 'Esther 7',
    explanation: 'Queen Esther risked her life to appeal to the king and save the Jewish people.'
  },
  // Job
  {
    id: 'job_001_01',
    collection: 'Old Testament',
    book: 'Job',
    chapter: 1,
    category: 'Suffering',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who lost everything but remained faithful to God?',
    choices: ['David', 'Solomon', 'Job', 'Abraham'],
    answer: 'Job',
    verse: 'Job 1:21',
    explanation: 'Job lost his family, wealth, and health but never cursed God.'
  },
  // Psalms
  {
    id: 'psa_023_01',
    collection: 'Old Testament',
    book: 'Psalms',
    chapter: 23,
    category: 'Praise',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who is described as a shepherd in Psalm 23?',
    choices: ['David', 'Moses', 'The Lord', 'Solomon'],
    answer: 'The Lord',
    verse: 'Psalm 23:1',
    explanation: 'The Lord is portrayed as a caring shepherd.'
  },
  // Proverbs
  {
    id: 'pro_001_01',
    collection: 'Old Testament',
    book: 'Proverbs',
    chapter: 1,
    category: 'Wisdom Principles',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'The fear of the Lord is the beginning of what?',
    choices: ['Power', 'Wealth', 'Knowledge', 'Happiness'],
    answer: 'Knowledge',
    verse: 'Proverbs 1:7',
    explanation: 'Proverbs 1:7 states: "The fear of the LORD is the beginning of knowledge."'
  },
  {
    id: 'pro_003_01',
    collection: 'Old Testament',
    book: 'Proverbs',
    chapter: 3,
    category: 'Wisdom Principles',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What should be trusted rather than one\'s own understanding?',
    choices: ['Strength', 'Wealth', 'The Lord', 'Knowledge'],
    answer: 'The Lord',
    verse: 'Proverbs 3:5',
    explanation: 'Believers are encouraged to trust God fully.'
  },
  // Ecclesiastes
  {
    id: 'ecc_001_01',
    collection: 'Old Testament',
    book: 'Ecclesiastes',
    chapter: 1,
    category: 'Meaning of Life',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What book says "Vanity of vanities, all is vanity"?',
    choices: ['Proverbs', 'Psalms', 'Ecclesiastes', 'Job'],
    answer: 'Ecclesiastes',
    verse: 'Ecclesiastes 1:2',
    explanation: 'Ecclesiastes explores the meaning of life and concludes many things are meaningless without God.'
  },
  // Isaiah
  {
    id: 'isa_007_01',
    collection: 'Old Testament',
    book: 'Isaiah',
    chapter: 7,
    category: 'Messianic Prophecy',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Which prophet foretold that a virgin would conceive and bear a son?',
    choices: ['Jeremiah', 'Ezekiel', 'Isaiah', 'Micah'],
    answer: 'Isaiah',
    verse: 'Isaiah 7:14',
    explanation: 'Isaiah prophesied about the virgin birth of Immanuel.'
  },
  // Jonah
  {
    id: 'jon_001_01',
    collection: 'Old Testament',
    book: 'Jonah',
    chapter: 1,
    category: 'Prophetic Obedience',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Which prophet was swallowed by a great fish?',
    choices: ['Isaiah', 'Jeremiah', 'Jonah', 'Ezekiel'],
    answer: 'Jonah',
    verse: 'Jonah 1:17',
    explanation: 'Jonah was swallowed by a great fish after fleeing from God\'s command to go to Nineveh.'
  },
  // Ezekiel
  {
    id: 'eze_037_01',
    collection: 'Old Testament',
    book: 'Ezekiel',
    chapter: 37,
    category: 'Visions of God',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Which prophet saw a vision of dry bones coming to life?',
    choices: ['Isaiah', 'Jeremiah', 'Daniel', 'Ezekiel'],
    answer: 'Ezekiel',
    verse: 'Ezekiel 37:1-14',
    explanation: 'Ezekiel saw the valley of dry bones as a vision of Israel\'s restoration.'
  },
  // Daniel
  {
    id: 'dan_006_01',
    collection: 'Old Testament',
    book: 'Daniel',
    chapter: 6,
    category: 'Faithfulness in Exile',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who was thrown into a den of lions for praying to God?',
    choices: ['Joseph', 'Daniel', 'David', 'Shadrach'],
    answer: 'Daniel',
    verse: 'Daniel 6',
    explanation: 'Daniel was thrown into the lions\' den but God sent an angel to shut the lions\' mouths.'
  },
  // Micah
  {
    id: 'mic_005_01',
    collection: 'Old Testament',
    book: 'Micah',
    chapter: 5,
    category: 'Messianic Hope',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Which prophet prophesied that Jesus would be born in Bethlehem?',
    choices: ['Isaiah', 'Micah', 'Zechariah', 'Malachi'],
    answer: 'Micah',
    verse: 'Micah 5:2',
    explanation: 'Micah prophesied that the ruler of Israel would come from Bethlehem.'
  },
  // Matthew
  {
    id: 'mat_002_01',
    collection: 'New Testament',
    book: 'Matthew',
    chapter: 2,
    category: 'Birth of Jesus',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Where was Jesus born?',
    choices: ['Nazareth', 'Jerusalem', 'Bethlehem', 'Galilee'],
    answer: 'Bethlehem',
    verse: 'Matthew 2:1',
    explanation: 'Jesus was born in Bethlehem of Judea.'
  },
  {
    id: 'mat_003_01',
    collection: 'New Testament',
    book: 'Matthew',
    chapter: 3,
    category: 'Teachings of Jesus',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who baptized Jesus?',
    choices: ['Peter', 'John the Baptist', 'James', 'Andrew'],
    answer: 'John the Baptist',
    verse: 'Matthew 3:13',
    explanation: 'John the Baptist baptized Jesus in the Jordan River.'
  },
  {
    id: 'mat_007_01',
    collection: 'New Testament',
    book: 'Matthew',
    chapter: 7,
    category: 'Parables',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What did the wise man build his house upon?',
    choices: ['Sand', 'Rock', 'Wood', 'Brick'],
    answer: 'Rock',
    verse: 'Matthew 7:24',
    explanation: 'Jesus taught that the wise man builds his house on the rock, representing obedience to His words.'
  },
  {
    id: 'mat_014_01',
    collection: 'New Testament',
    book: 'Matthew',
    chapter: 14,
    category: 'Miracles',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Which disciple walked on water with Jesus?',
    choices: ['James', 'John', 'Peter', 'Thomas'],
    answer: 'Peter',
    verse: 'Matthew 14:29',
    explanation: 'Peter walked on the water to go to Jesus, but began to sink when he saw the wind.'
  },
  {
    id: 'mat_026_01',
    collection: 'New Testament',
    book: 'Matthew',
    chapter: 26,
    category: 'Crucifixion',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who betrayed Jesus for 30 pieces of silver?',
    choices: ['Peter', 'Judas', 'Thomas', 'James'],
    answer: 'Judas',
    verse: 'Matthew 26:15',
    explanation: 'Judas Iscariot betrayed Jesus for 30 pieces of silver.'
  },
  // Mark
  {
    id: 'mrk_003_01',
    collection: 'New Testament',
    book: 'Mark',
    chapter: 3,
    category: 'Discipleship',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'How many disciples did Jesus choose?',
    choices: ['7', '10', '12', '70'],
    answer: '12',
    verse: 'Mark 3:14',
    explanation: 'Jesus chose 12 disciples to be with Him and to be sent out to preach.'
  },
  {
    id: 'mrk_005_01',
    collection: 'New Testament',
    book: 'Mark',
    chapter: 5,
    category: 'Miracles',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Whose daughter did Jesus raise from the dead?',
    choices: ['Peter\'s', 'Jairus\'s', 'Lazarus\'s', 'Martha\'s'],
    answer: 'Jairus\'s',
    verse: 'Mark 5:22-42',
    explanation: 'Jesus raised the daughter of Jairus, a synagogue leader, from the dead.'
  },
  {
    id: 'mrk_006_01',
    collection: 'New Testament',
    book: 'Mark',
    chapter: 6,
    category: 'Miracles',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'How many baskets of leftovers were gathered after feeding the 5,000?',
    choices: ['7', '3', '12', '5'],
    answer: '12',
    verse: 'Mark 6:43',
    explanation: 'They gathered 12 baskets full of broken pieces and of the fish.'
  },
  {
    id: 'mrk_015_01',
    collection: 'New Testament',
    book: 'Mark',
    chapter: 15,
    category: 'Passion Narrative',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Who helped carry Jesus\' cross?',
    choices: ['Peter', 'John', 'Simon of Cyrene', 'Joseph'],
    answer: 'Simon of Cyrene',
    verse: 'Mark 15:21',
    explanation: 'Simon of Cyrene was compelled to carry Jesus\' cross.'
  },
  {
    id: 'mrk_016_01',
    collection: 'New Testament',
    book: 'Mark',
    chapter: 16,
    category: 'Resurrection',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who was the first person to see the risen Jesus?',
    choices: ['Peter', 'John', 'Mary Magdalene', 'Thomas'],
    answer: 'Mary Magdalene',
    verse: 'Mark 16:9',
    explanation: 'Jesus appeared first to Mary Magdalene on resurrection morning.'
  },
  // Luke
  {
    id: 'luk_001_01',
    collection: 'New Testament',
    book: 'Luke',
    chapter: 1,
    category: 'Birth Narratives',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who was the mother of John the Baptist?',
    choices: ['Mary', 'Elizabeth', 'Anna', 'Martha'],
    answer: 'Elizabeth',
    verse: 'Luke 1:57',
    explanation: 'Elizabeth, a relative of Mary, was the mother of John the Baptist.'
  },
  {
    id: 'luk_008_01',
    collection: 'New Testament',
    book: 'Luke',
    chapter: 8,
    category: 'Teachings',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'In the parable of the Sower, what does the seed represent?',
    choices: ['Money', 'Faith', 'The Word of God', 'Good Deeds'],
    answer: 'The Word of God',
    verse: 'Luke 8:11',
    explanation: 'The seed is the word of God.'
  },
  {
    id: 'luk_010_01',
    collection: 'New Testament',
    book: 'Luke',
    chapter: 10,
    category: 'Compassion of Jesus',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'In the parable of the Good Samaritan, who helped the injured man?',
    choices: ['A priest', 'A Levite', 'A Samaritan', 'A Roman soldier'],
    answer: 'A Samaritan',
    verse: 'Luke 10:33',
    explanation: 'While the priest and Levite passed by, the Samaritan showed mercy to the injured man.'
  },
  {
    id: 'luk_015_01',
    collection: 'New Testament',
    book: 'Luke',
    chapter: 15,
    category: 'Teachings',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'In the parable of the Prodigal Son, what did the father do when he saw his son returning?',
    choices: ['Scolded him', 'Ignored him', 'Ran to him', 'Locked the door'],
    answer: 'Ran to him',
    verse: 'Luke 15:20',
    explanation: 'While he was still a long way off, his father saw him and felt compassion, and ran and embraced him.'
  },
  // John
  {
    id: 'jhn_002_01',
    collection: 'New Testament',
    book: 'John',
    chapter: 2,
    category: 'Signs of Jesus',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What was the first miracle Jesus performed?',
    choices: ['Healing a leper', 'Turning water into wine', 'Feeding the 5000', 'Walking on water'],
    answer: 'Turning water into wine',
    verse: 'John 2:11',
    explanation: 'Jesus turned water into wine at the wedding in Cana.'
  },
  {
    id: 'jhn_003_01',
    collection: 'New Testament',
    book: 'John',
    chapter: 3,
    category: 'Eternal Life',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who came to Jesus at night to ask about being born again?',
    choices: ['Peter', 'Nicodemus', 'Pilate', 'Joseph'],
    answer: 'Nicodemus',
    verse: 'John 3:1-2',
    explanation: 'Nicodemus, a Pharisee, came to Jesus at night and learned about spiritual rebirth.'
  },
  // Acts
  {
    id: 'act_002_01',
    collection: 'New Testament',
    book: 'Acts',
    chapter: 2,
    category: 'Holy Spirit',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What event happened on the Day of Pentecost?',
    choices: ['Jesus ascended', 'The Holy Spirit came', 'The temple was destroyed', 'Paul was converted'],
    answer: 'The Holy Spirit came',
    verse: 'Acts 2:3-4',
    explanation: 'The Holy Spirit came upon the disciples on Pentecost with tongues of fire.'
  },
  {
    id: 'act_007_01',
    collection: 'New Testament',
    book: 'Acts',
    chapter: 7,
    category: 'Early Church',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Who was the first Christian martyr?',
    choices: ['Peter', 'James', 'Stephen', 'Paul'],
    answer: 'Stephen',
    verse: 'Acts 7:59',
    explanation: 'Stephen was stoned to death for his faith, becoming the first Christian martyr.'
  },
  {
    id: 'act_009_01',
    collection: 'New Testament',
    book: 'Acts',
    chapter: 9,
    category: 'Paul\'s Missions',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What was Paul\'s name before his conversion?',
    choices: ['Simon', 'Saul', 'Samuel', 'Seth'],
    answer: 'Saul',
    verse: 'Acts 9:1',
    explanation: 'Paul was known as Saul before his encounter with Jesus on the road to Damascus.'
  },
  // Romans
  {
    id: 'rom_001_01',
    collection: 'New Testament',
    book: 'Romans',
    chapter: 1,
    category: 'Sin and Salvation',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who wrote the majority of the Epistles in the New Testament?',
    choices: ['Peter', 'James', 'Paul', 'John'],
    answer: 'Paul',
    verse: 'Romans 1:1',
    explanation: 'The Apostle Paul wrote at least 13 books of the New Testament.'
  },
  {
    id: 'rom_006_01',
    collection: 'New Testament',
    book: 'Romans',
    chapter: 6,
    category: 'Sin and Salvation',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'According to Romans, what is the wages of sin?',
    choices: ['Suffering', 'Death', 'Poverty', 'Loneliness'],
    answer: 'Death',
    verse: 'Romans 6:23',
    explanation: 'The wages of sin is death, but the gift of God is eternal life in Christ Jesus.'
  },
  // 1 Corinthians
  {
    id: '1co_013_01',
    collection: 'New Testament',
    book: '1 Corinthians',
    chapter: 13,
    category: 'Love',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'In 1 Corinthians 13, what is described as the greatest virtue?',
    choices: ['Faith', 'Hope', 'Love', 'Wisdom'],
    answer: 'Love',
    verse: '1 Corinthians 13:13',
    explanation: 'Paul says the greatest of faith, hope, and love is love.'
  },
  // Hebrews
  {
    id: 'heb_006_01',
    collection: 'New Testament',
    book: 'Hebrews',
    chapter: 6,
    category: 'Supremacy of Christ',
    difficulty: 'hard',
    type: 'multiple-choice',
    question: 'Which book calls Jesus a high priest forever in the order of Melchizedek?',
    choices: ['Romans', 'Hebrews', 'James', '1 Peter'],
    answer: 'Hebrews',
    verse: 'Hebrews 6:20',
    explanation: 'Hebrews describes Jesus as a high priest in the order of Melchizedek.'
  },
  // James
  {
    id: 'jas_002_01',
    collection: 'New Testament',
    book: 'James',
    chapter: 2,
    category: 'Practical Faith',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'According to James, faith without works is what?',
    choices: ['Strong', 'Dead', 'Pure', 'Sufficient'],
    answer: 'Dead',
    verse: 'James 2:26',
    explanation: 'James teaches that faith without works is dead.'
  },
  // Revelation
  {
    id: 'rev_002_01',
    collection: 'New Testament',
    book: 'Revelation',
    chapter: 2,
    category: 'Letters to the Churches',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'How many churches received letters in Revelation?',
    choices: ['5', '7', '10', '12'],
    answer: '7',
    verse: 'Revelation 2-3',
    explanation: 'Jesus sent letters to seven churches in Asia Minor.'
  },
  {
    id: 'rev_021_01',
    collection: 'New Testament',
    book: 'Revelation',
    chapter: 21,
    category: 'New Creation',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'In Revelation, what is the name of the city that comes down from heaven?',
    choices: ['New Babylon', 'New Jerusalem', 'Zion', 'Eden'],
    answer: 'New Jerusalem',
    verse: 'Revelation 21:2',
    explanation: 'John saw the Holy City, the new Jerusalem, coming down out of heaven from God.'
  },
  // Additional Genesis questions
  {
    id: 'gen_015_01',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 15,
    category: 'Covenants',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What did God promise Abram regarding his descendants?',
    choices: ['They would be priests', 'They would be as numerous as the stars', 'They would rule Egypt', 'They would never suffer'],
    answer: 'They would be as numerous as the stars',
    verse: 'Genesis 15:5',
    explanation: 'God promised Abram countless descendants.'
  },
  {
    id: 'gen_022_02',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 22,
    category: 'Patriarchs',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Whom did God ask Abraham to offer as a sacrifice?',
    choices: ['Ishmael', 'Isaac', 'Jacob', 'Eliezer'],
    answer: 'Isaac',
    verse: 'Genesis 22:2',
    explanation: 'God tested Abraham\'s faith by asking him to offer Isaac.'
  },
  {
    id: 'gen_028_01',
    collection: 'Old Testament',
    book: 'Genesis',
    chapter: 28,
    category: 'Patriarchs',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What did Jacob see in his dream at Bethel?',
    choices: ['A burning bush', 'A ladder reaching to heaven', 'A river of fire', 'A throne'],
    answer: 'A ladder reaching to heaven',
    verse: 'Genesis 28:12',
    explanation: 'Jacob dreamed of a ladder with angels ascending and descending.'
  },
  // Additional Exodus questions
  {
    id: 'exo_012_02',
    collection: 'Old Testament',
    book: 'Exodus',
    chapter: 12,
    category: 'Passover',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What kind of animal was required for the Passover sacrifice?',
    choices: ['A bull', 'A goat or lamb without defect', 'A dove', 'A ram'],
    answer: 'A goat or lamb without defect',
    verse: 'Exodus 12:5',
    explanation: 'The Passover animal had to be without blemish.'
  },
  {
    id: 'exo_019_01',
    collection: 'Old Testament',
    book: 'Exodus',
    chapter: 19,
    category: 'Law at Sinai',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Where did God give the law to Moses?',
    choices: ['Mount Horeb', 'Mount Sinai', 'Mount Carmel', 'Mount Nebo'],
    answer: 'Mount Sinai',
    verse: 'Exodus 19:20',
    explanation: 'God descended on Mount Sinai to give His law.'
  },
  {
    id: 'exo_040_01',
    collection: 'Old Testament',
    book: 'Exodus',
    chapter: 40,
    category: 'Tabernacle',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What sign showed that God\'s glory filled the tabernacle?',
    choices: ['Fire from heaven', 'A cloud covering it', 'Thunder and lightning', 'Angels singing'],
    answer: 'A cloud covering it',
    verse: 'Exodus 40:34',
    explanation: 'The cloud represented God\'s presence dwelling among Israel.'
  },
  // Additional Leviticus questions
  {
    id: 'lev_010_01',
    collection: 'Old Testament',
    book: 'Leviticus',
    chapter: 10,
    category: 'Priesthood',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Which two sons of Aaron died for offering unauthorized fire?',
    choices: ['Eleazar and Ithamar', 'Nadab and Abihu', 'Phinehas and Eleazar', 'Moses and Aaron'],
    answer: 'Nadab and Abihu',
    verse: 'Leviticus 10:1-2',
    explanation: 'They disobeyed God\'s instructions for worship.'
  },
  // Additional Numbers questions
  {
    id: 'num_006_01',
    collection: 'Old Testament',
    book: 'Numbers',
    chapter: 6,
    category: 'Law',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Who could take a Nazirite vow?',
    choices: ['Only priests', 'Only Levites', 'Any Israelite', 'Only prophets'],
    answer: 'Any Israelite',
    verse: 'Numbers 6:2',
    explanation: 'The Nazirite vow was open to all Israelites.'
  },
  {
    id: 'num_021_01',
    collection: 'Old Testament',
    book: 'Numbers',
    chapter: 21,
    category: 'Wilderness Wanderings',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What did Moses lift up to heal the people from snake bites?',
    choices: ['A staff', 'A bronze serpent', 'An altar', 'A banner'],
    answer: 'A bronze serpent',
    verse: 'Numbers 21:9',
    explanation: 'Those who looked at the bronze serpent were healed.'
  },
  // Additional Deuteronomy questions
  {
    id: 'deu_008_01',
    collection: 'Old Testament',
    book: 'Deuteronomy',
    chapter: 8,
    category: 'Blessings and Curses',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Why did God allow Israel to hunger in the wilderness?',
    choices: ['To punish them', 'To humble and test them', 'Because of scarcity', 'Because of enemies'],
    answer: 'To humble and test them',
    verse: 'Deuteronomy 8:2-3',
    explanation: 'God used the wilderness to teach dependence on Him.'
  },
  // Additional Joshua questions
  {
    id: 'jos_024_01',
    collection: 'Old Testament',
    book: 'Joshua',
    chapter: 24,
    category: 'Covenant Renewal',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What did Joshua challenge Israel to choose?',
    choices: ['A king', 'A land', 'Whom they would serve', 'A new law'],
    answer: 'Whom they would serve',
    verse: 'Joshua 24:15',
    explanation: 'Joshua urged Israel to serve the Lord alone.'
  },
  // Additional Judges questions
  {
    id: 'jud_004_02',
    collection: 'Old Testament',
    book: 'Judges',
    chapter: 4,
    category: 'Major Judges',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Who was the female judge who led Israel to victory?',
    choices: ['Ruth', 'Deborah', 'Jael', 'Miriam'],
    answer: 'Deborah',
    verse: 'Judges 4:4',
    explanation: 'Deborah served as both prophet and judge.'
  },
  // Additional 1 Samuel questions
  {
    id: '1sa_003_01',
    collection: 'Old Testament',
    book: '1 Samuel',
    chapter: 3,
    category: 'Samuel\'s Leadership',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who called Samuel during the night?',
    choices: ['Eli', 'The Lord', 'Saul', 'An angel'],
    answer: 'The Lord',
    verse: '1 Samuel 3:10',
    explanation: 'God called Samuel to be His prophet.'
  },
  // Additional 1 Kings questions
  {
    id: '1ki_008_01',
    collection: 'Old Testament',
    book: '1 Kings',
    chapter: 8,
    category: 'Temple Construction',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Who dedicated the temple in Jerusalem?',
    choices: ['David', 'Solomon', 'Rehoboam', 'Josiah'],
    answer: 'Solomon',
    verse: '1 Kings 8:22',
    explanation: 'Solomon prayed and dedicated the temple to the Lord.'
  },
  // Additional 2 Kings questions
  {
    id: '2ki_017_01',
    collection: 'Old Testament',
    book: '2 Kings',
    chapter: 17,
    category: 'Exile',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Why was the northern kingdom of Israel exiled?',
    choices: ['Military weakness', 'Disobedience to God', 'Natural disaster', 'Economic failure'],
    answer: 'Disobedience to God',
    verse: '2 Kings 17:7-8',
    explanation: 'Israel broke God\'s covenant and followed other gods.'
  },
  // Additional Psalms questions
  {
    id: 'psa_051_01',
    collection: 'Old Testament',
    book: 'Psalms',
    chapter: 51,
    category: 'Lament',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'After which sin did David write Psalm 51?',
    choices: ['Census of Israel', 'Sin with Bathsheba', 'Fleeing Saul', 'Failing to build the temple'],
    answer: 'Sin with Bathsheba',
    verse: 'Psalm 51:1',
    explanation: 'Psalm 51 is David\'s prayer of repentance.'
  },
  // Additional Proverbs questions
  {
    id: 'pro_001_02',
    collection: 'Old Testament',
    book: 'Proverbs',
    chapter: 1,
    category: 'Wisdom Principles',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What is the beginning of knowledge according to Proverbs?',
    choices: ['Education', 'Experience', 'Fear of the Lord', 'Understanding'],
    answer: 'Fear of the Lord',
    verse: 'Proverbs 1:7',
    explanation: 'Reverence for God is the foundation of wisdom.'
  },
  // Additional New Testament questions
  {
    id: 'mat_001_01',
    collection: 'New Testament',
    book: 'Matthew',
    chapter: 1,
    category: 'Birth of Jesus',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who was the mother of Jesus?',
    choices: ['Elizabeth', 'Mary', 'Martha', 'Anna'],
    answer: 'Mary',
    verse: 'Matthew 1:18',
    explanation: 'Mary conceived Jesus through the Holy Spirit.'
  },
  {
    id: 'mat_002_02',
    collection: 'New Testament',
    book: 'Matthew',
    chapter: 2,
    category: 'Birth of Jesus',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who visited Jesus after His birth according to Matthew?',
    choices: ['Shepherds', 'Wise men', 'Priests', 'Levites'],
    answer: 'Wise men',
    verse: 'Matthew 2:1',
    explanation: 'Wise men from the east came to worship Jesus.'
  },
  {
    id: 'mat_004_01',
    collection: 'New Testament',
    book: 'Matthew',
    chapter: 4,
    category: 'Teachings of Jesus',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'How many times was Jesus tempted in the wilderness?',
    choices: ['One', 'Two', 'Three', 'Four'],
    answer: 'Three',
    verse: 'Matthew 4:1-11',
    explanation: 'Jesus faced three temptations and resisted each one.'
  },
  {
    id: 'mat_005_01',
    collection: 'New Testament',
    book: 'Matthew',
    chapter: 5,
    category: 'Teachings of Jesus',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What sermon begins in Matthew chapter 5?',
    choices: ['The Olivet Discourse', 'The Sermon on the Mount', 'The Parable Sermon', 'The Farewell Discourse'],
    answer: 'The Sermon on the Mount',
    verse: 'Matthew 5:1-2',
    explanation: 'Jesus taught His disciples on a mountainside.'
  },
  {
    id: 'mat_013_01',
    collection: 'New Testament',
    book: 'Matthew',
    chapter: 13,
    category: 'Parables',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Which parable describes seed falling on different types of soil?',
    choices: ['The Mustard Seed', 'The Sower', 'The Hidden Treasure', 'The Net'],
    answer: 'The Sower',
    verse: 'Matthew 13:3-8',
    explanation: 'The parable explains different responses to God\'s word.'
  },
  {
    id: 'mat_014_02',
    collection: 'New Testament',
    book: 'Matthew',
    chapter: 14,
    category: 'Miracles',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What miracle did Jesus perform to feed a large crowd?',
    choices: ['Turning water into wine', 'Feeding five thousand', 'Raising Lazarus', 'Healing a blind man'],
    answer: 'Feeding five thousand',
    verse: 'Matthew 14:19-21',
    explanation: 'Jesus multiplied loaves and fish to feed the crowd.'
  },
  {
    id: 'mar_001_01',
    collection: 'New Testament',
    book: 'Mark',
    chapter: 1,
    category: 'Servant Messiah',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who baptized Jesus?',
    choices: ['Peter', 'John the Baptist', 'Andrew', 'James'],
    answer: 'John the Baptist',
    verse: 'Mark 1:9',
    explanation: 'Jesus was baptized by John in the Jordan River.'
  },
  {
    id: 'mar_002_01',
    collection: 'New Testament',
    book: 'Mark',
    chapter: 2,
    category: 'Miracles',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'How was the paralyzed man brought to Jesus?',
    choices: ['Through a crowd', 'Lowered through the roof', 'Carried by priests', 'Brought at night'],
    answer: 'Lowered through the roof',
    verse: 'Mark 2:4',
    explanation: 'Friends lowered the man through the roof to reach Jesus.'
  },
  {
    id: 'luk_002_02',
    collection: 'New Testament',
    book: 'Luke',
    chapter: 2,
    category: 'Birth Narratives',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Where was Jesus born?',
    choices: ['Nazareth', 'Bethlehem', 'Jerusalem', 'Capernaum'],
    answer: 'Bethlehem',
    verse: 'Luke 2:4-7',
    explanation: 'Jesus was born in Bethlehem, fulfilling prophecy.'
  },
  {
    id: 'luk_010_02',
    collection: 'New Testament',
    book: 'Luke',
    chapter: 10,
    category: 'Parables',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Who helped the injured man in the parable of the Good Samaritan?',
    choices: ['A priest', 'A Levite', 'A Samaritan', 'A soldier'],
    answer: 'A Samaritan',
    verse: 'Luke 10:33',
    explanation: 'Jesus taught love for one\'s neighbor through this parable.'
  },
  {
    id: 'jhn_001_01',
    collection: 'New Testament',
    book: 'John',
    chapter: 1,
    category: 'Eternal Life',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What title is given to Jesus in John 1:1?',
    choices: ['The Prophet', 'The Word', 'The Light', 'The Lamb'],
    answer: 'The Word',
    verse: 'John 1:1',
    explanation: 'Jesus is described as the eternal Word of God.'
  },
  {
    id: 'jhn_002_02',
    collection: 'New Testament',
    book: 'John',
    chapter: 2,
    category: 'Signs of Jesus',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What was Jesus\' first recorded miracle?',
    choices: ['Healing a blind man', 'Walking on water', 'Turning water into wine', 'Feeding the crowd'],
    answer: 'Turning water into wine',
    verse: 'John 2:11',
    explanation: 'Jesus performed His first sign at a wedding in Cana.'
  },
  {
    id: 'act_002_02',
    collection: 'New Testament',
    book: 'Acts',
    chapter: 2,
    category: 'Holy Spirit',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What event occurred on the Day of Pentecost?',
    choices: ['Jesus ascended', 'The Holy Spirit descended', 'Paul was converted', 'The church scattered'],
    answer: 'The Holy Spirit descended',
    verse: 'Acts 2:4',
    explanation: 'The Holy Spirit empowered the believers.'
  },
  {
    id: 'rom_003_01',
    collection: 'New Testament',
    book: 'Romans',
    chapter: 3,
    category: 'Sin and Salvation',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What does Paul say all people have done?',
    choices: ['Obeyed the law', 'Sinned', 'Believed immediately', 'Repented fully'],
    answer: 'Sinned',
    verse: 'Romans 3:23',
    explanation: 'All have sinned and fall short of God\'s glory.'
  },
  {
    id: '1co_013_02',
    collection: 'New Testament',
    book: '1 Corinthians',
    chapter: 13,
    category: 'Love',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Which virtue is emphasized in 1 Corinthians 13?',
    choices: ['Faith', 'Hope', 'Love', 'Knowledge'],
    answer: 'Love',
    verse: '1 Corinthians 13:13',
    explanation: 'Love is described as the greatest virtue.'
  },
  {
    id: 'eph_002_01',
    collection: 'New Testament',
    book: 'Ephesians',
    chapter: 2,
    category: 'Salvation',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'How does Paul say people are saved?',
    choices: ['By works', 'By the law', 'By grace through faith', 'By heritage'],
    answer: 'By grace through faith',
    verse: 'Ephesians 2:8',
    explanation: 'Salvation is God\'s gift, not earned.'
  },
  {
    id: 'heb_011_01',
    collection: 'New Testament',
    book: 'Hebrews',
    chapter: 11,
    category: 'Faith',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What is faith described as in Hebrews 11?',
    choices: ['Good behavior', 'Certainty without evidence', 'Confidence in what we hope for', 'Obedience to rules'],
    answer: 'Confidence in what we hope for',
    verse: 'Hebrews 11:1',
    explanation: 'Faith involves trust in God\'s promises.'
  },
  {
    id: 'jas_001_01',
    collection: 'New Testament',
    book: 'James',
    chapter: 1,
    category: 'Practical Faith',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What should believers ask God for according to James?',
    choices: ['Wealth', 'Wisdom', 'Strength', 'Patience'],
    answer: 'Wisdom',
    verse: 'James 1:5',
    explanation: 'God gives wisdom generously to those who ask.'
  },
  {
    id: 'rev_021_02',
    collection: 'New Testament',
    book: 'Revelation',
    chapter: 21,
    category: 'New Creation',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What does John see coming down from heaven?',
    choices: ['A great throne', 'The new Jerusalem', 'A scroll', 'A river of fire'],
    answer: 'The new Jerusalem',
    verse: 'Revelation 21:2',
    explanation: 'John sees the holy city prepared by God.'
  },
  // More Acts questions
  {
    id: 'act_009_01',
    collection: 'New Testament',
    book: 'Acts',
    chapter: 9,
    category: 'Paul\'s Missions',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who was converted on the road to Damascus?',
    choices: ['Peter', 'Barnabas', 'Saul', 'Stephen'],
    answer: 'Saul',
    verse: 'Acts 9:3-4',
    explanation: 'Saul encountered Jesus and later became known as Paul.'
  },
  {
    id: 'act_016_01',
    collection: 'New Testament',
    book: 'Acts',
    chapter: 16,
    category: 'Paul\'s Missions',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Where was Paul imprisoned when an earthquake opened the doors?',
    choices: ['Rome', 'Philippi', 'Corinth', 'Ephesus'],
    answer: 'Philippi',
    verse: 'Acts 16:25-26',
    explanation: 'Paul and Silas were imprisoned in Philippi.'
  },
  // More Romans questions
  {
    id: 'rom_005_01',
    collection: 'New Testament',
    book: 'Romans',
    chapter: 5,
    category: 'Justification by Faith',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What brings peace with God according to Romans 5?',
    choices: ['Good works', 'The law', 'Justification by faith', 'Obedience'],
    answer: 'Justification by faith',
    verse: 'Romans 5:1',
    explanation: 'Believers have peace with God through faith in Christ.'
  },
  {
    id: 'rom_008_01',
    collection: 'New Testament',
    book: 'Romans',
    chapter: 8,
    category: 'Christian Living',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What is there now for those who are in Christ Jesus?',
    choices: ['Condemnation', 'Judgment', 'No condemnation', 'Fear'],
    answer: 'No condemnation',
    verse: 'Romans 8:1',
    explanation: 'Paul emphasizes freedom from condemnation in Christ.'
  },
  // 1 Corinthians
  {
    id: '1co_015_01',
    collection: 'New Testament',
    book: '1 Corinthians',
    chapter: 15,
    category: 'Resurrection',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What central doctrine is addressed in 1 Corinthians 15?',
    choices: ['Spiritual gifts', 'The resurrection', 'Church order', 'Love'],
    answer: 'The resurrection',
    verse: '1 Corinthians 15:12',
    explanation: 'Paul defends the resurrection of the dead.'
  },
  // 2 Corinthians
  {
    id: '2co_005_01',
    collection: 'New Testament',
    book: '2 Corinthians',
    chapter: 5,
    category: 'Apostolic Ministry',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'How does Paul describe anyone who is in Christ?',
    choices: ['A servant', 'A new creation', 'A disciple', 'A witness'],
    answer: 'A new creation',
    verse: '2 Corinthians 5:17',
    explanation: 'In Christ, the old has gone and the new has come.'
  },
  // Galatians
  {
    id: 'gal_005_01',
    collection: 'New Testament',
    book: 'Galatians',
    chapter: 5,
    category: 'Freedom in Christ',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What fruit of the Spirit is listed in Galatians 5?',
    choices: ['Strength', 'Love', 'Boldness', 'Authority'],
    answer: 'Love',
    verse: 'Galatians 5:22',
    explanation: 'Love is listed first among the fruit of the Spirit.'
  },
  // Ephesians
  {
    id: 'eph_006_01',
    collection: 'New Testament',
    book: 'Ephesians',
    chapter: 6,
    category: 'Christian Conduct',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What metaphor does Paul use to describe spiritual preparedness?',
    choices: ['A race', 'Armor', 'A harvest', 'A journey'],
    answer: 'Armor',
    verse: 'Ephesians 6:11',
    explanation: 'Believers are urged to put on the full armor of God.'
  },
  // Philippians
  {
    id: 'phi_002_01',
    collection: 'New Testament',
    book: 'Philippians',
    chapter: 2,
    category: 'Humility of Christ',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What attitude does Paul encourage believers to have?',
    choices: ['Pride', 'Humility', 'Boldness', 'Independence'],
    answer: 'Humility',
    verse: 'Philippians 2:5',
    explanation: 'Believers are called to have the same mindset as Christ.'
  },
  // Colossians
  {
    id: 'col_001_01',
    collection: 'New Testament',
    book: 'Colossians',
    chapter: 1,
    category: 'Supremacy of Christ',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'How is Christ described in relation to creation?',
    choices: ['Part of creation', 'First created being', 'Supreme over creation', 'A teacher of creation'],
    answer: 'Supreme over creation',
    verse: 'Colossians 1:16-17',
    explanation: 'All things were created through Christ and for Him.'
  },
  // 1 Thessalonians
  {
    id: '1th_004_01',
    collection: 'New Testament',
    book: '1 Thessalonians',
    chapter: 4,
    category: 'Second Coming',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What event does Paul describe in 1 Thessalonians 4?',
    choices: ['The crucifixion', 'The resurrection of Lazarus', 'The return of the Lord', 'Pentecost'],
    answer: 'The return of the Lord',
    verse: '1 Thessalonians 4:16',
    explanation: 'Paul describes the Lord\'s return and the resurrection.'
  },
  // 2 Thessalonians
  {
    id: '2th_002_01',
    collection: 'New Testament',
    book: '2 Thessalonians',
    chapter: 2,
    category: 'End Times',
    difficulty: 'hard',
    type: 'multiple-choice',
    question: 'What must occur before the day of the Lord?',
    choices: ['A great revival', 'The rebellion', 'World peace', 'Temple rebuilding'],
    answer: 'The rebellion',
    verse: '2 Thessalonians 2:3',
    explanation: 'Paul explains events preceding the day of the Lord.'
  },
  // 1 Timothy
  {
    id: '1ti_003_01',
    collection: 'New Testament',
    book: '1 Timothy',
    chapter: 3,
    category: 'Church Leadership',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Which quality is required of overseers?',
    choices: ['Wealthy', 'Above reproach', 'Highly educated', 'Politically skilled'],
    answer: 'Above reproach',
    verse: '1 Timothy 3:2',
    explanation: 'Church leaders are held to a high moral standard.'
  },
  // 2 Timothy
  {
    id: '2ti_003_01',
    collection: 'New Testament',
    book: '2 Timothy',
    chapter: 3,
    category: 'Scripture',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'How is Scripture described by Paul?',
    choices: ['Inspired by teachers', 'Written for history', 'God-breathed', 'Symbolic only'],
    answer: 'God-breathed',
    verse: '2 Timothy 3:16',
    explanation: 'Scripture is inspired by God and useful for teaching.'
  },
  // Titus
  {
    id: 'tit_002_01',
    collection: 'New Testament',
    book: 'Titus',
    chapter: 2,
    category: 'Good Works',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Why should believers live self-controlled lives?',
    choices: ['To earn salvation', 'To set an example', 'To avoid hardship', 'To gain authority'],
    answer: 'To set an example',
    verse: 'Titus 2:7',
    explanation: 'Believers are called to model good works.'
  },
  // Philemon
  {
    id: 'phm_001_01',
    collection: 'New Testament',
    book: 'Philemon',
    chapter: 1,
    category: 'Forgiveness',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Who is the runaway slave mentioned in Philemon?',
    choices: ['Epaphras', 'Onesimus', 'Timothy', 'Silas'],
    answer: 'Onesimus',
    verse: 'Philemon 1:10',
    explanation: 'Paul appeals for Onesimus to be received as a brother.'
  },
  // 1 Peter
  {
    id: '1pe_001_01',
    collection: 'New Testament',
    book: '1 Peter',
    chapter: 1,
    category: 'Christian Hope',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What kind of hope do believers have?',
    choices: ['Temporary', 'Uncertain', 'Living', 'Earthly'],
    answer: 'Living',
    verse: '1 Peter 1:3',
    explanation: 'Believers are born again into a living hope.'
  },
  // 1 John
  {
    id: '1jn_004_01',
    collection: 'New Testament',
    book: '1 John',
    chapter: 4,
    category: 'Love',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What does John say God is?',
    choices: ['Light', 'Spirit', 'Love', 'Truth'],
    answer: 'Love',
    verse: '1 John 4:8',
    explanation: 'God\'s nature is defined as love.'
  },
  // Jude
  {
    id: 'jud_001_01',
    collection: 'New Testament',
    book: 'Jude',
    chapter: 1,
    category: 'Contending for the Faith',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What are believers urged to contend for?',
    choices: ['Tradition', 'The faith', 'Authority', 'Unity'],
    answer: 'The faith',
    verse: 'Jude 1:3',
    explanation: 'Jude urges believers to defend the true faith.'
  },
  // More Luke questions
  {
    id: 'luk_015_01',
    collection: 'New Testament',
    book: 'Luke',
    chapter: 15,
    category: 'Parables',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Which parable describes a son who leaves home and later returns?',
    choices: ['The Lost Sheep', 'The Lost Coin', 'The Prodigal Son', 'The Rich Fool'],
    answer: 'The Prodigal Son',
    verse: 'Luke 15:11-24',
    explanation: 'Jesus tells of a son who is welcomed back by his father.'
  },
  {
    id: 'luk_018_01',
    collection: 'New Testament',
    book: 'Luke',
    chapter: 18,
    category: 'Prayer',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Why did Jesus tell the parable of the persistent widow?',
    choices: ['To explain justice', 'To teach persistence in prayer', 'To warn judges', 'To show mercy'],
    answer: 'To teach persistence in prayer',
    verse: 'Luke 18:1',
    explanation: 'Jesus taught that believers should always pray and not give up.'
  },
  // More John questions
  {
    id: 'jhn_003_01',
    collection: 'New Testament',
    book: 'John',
    chapter: 3,
    category: 'Salvation',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Who visited Jesus at night to ask about being born again?',
    choices: ['Joseph of Arimathea', 'Nicodemus', 'Andrew', 'Philip'],
    answer: 'Nicodemus',
    verse: 'John 3:1-2',
    explanation: 'Nicodemus was a Pharisee who sought understanding from Jesus.'
  },
  {
    id: 'jhn_004_01',
    collection: 'New Testament',
    book: 'John',
    chapter: 4,
    category: 'Witness',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'With whom did Jesus speak at Jacob\'s well?',
    choices: ['A Samaritan woman', 'Mary Magdalene', 'A Roman official', 'A Jewish teacher'],
    answer: 'A Samaritan woman',
    verse: 'John 4:7',
    explanation: 'Jesus spoke with a Samaritan woman about living water.'
  },
  {
    id: 'jhn_006_01',
    collection: 'New Testament',
    book: 'John',
    chapter: 6,
    category: 'Teachings of Jesus',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What does Jesus call Himself in John 6?',
    choices: ['The Light of the World', 'The Bread of Life', 'The Good Shepherd', 'The True Vine'],
    answer: 'The Bread of Life',
    verse: 'John 6:35',
    explanation: 'Jesus teaches that He is essential for spiritual life.'
  },
  {
    id: 'jhn_010_02',
    collection: 'New Testament',
    book: 'John',
    chapter: 10,
    category: 'Identity of Jesus',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'How does Jesus describe Himself in John 10?',
    choices: ['The True Vine', 'The Good Shepherd', 'The Resurrection', 'The Way'],
    answer: 'The Good Shepherd',
    verse: 'John 10:11',
    explanation: 'Jesus explains His care and sacrifice for His followers.'
  },
  {
    id: 'jhn_011_01',
    collection: 'New Testament',
    book: 'John',
    chapter: 11,
    category: 'Miracles',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'Whom did Jesus raise from the dead in Bethany?',
    choices: ['Jairus\' daughter', 'The widow\'s son', 'Lazarus', 'Stephen'],
    answer: 'Lazarus',
    verse: 'John 11:43-44',
    explanation: 'Jesus raised Lazarus after four days in the tomb.'
  },
  {
    id: 'jhn_013_01',
    collection: 'New Testament',
    book: 'John',
    chapter: 13,
    category: 'Servanthood',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What did Jesus do to demonstrate servanthood?',
    choices: ['He fed the poor', 'He healed the sick', 'He washed the disciples\' feet', 'He taught in parables'],
    answer: 'He washed the disciples\' feet',
    verse: 'John 13:5',
    explanation: 'Jesus modeled humble service to His disciples.'
  },
  {
    id: 'jhn_014_02',
    collection: 'New Testament',
    book: 'John',
    chapter: 14,
    category: 'Comfort and Promise',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What does Jesus promise to prepare for His followers?',
    choices: ['A kingdom on earth', 'A place', 'A throne', 'A reward'],
    answer: 'A place',
    verse: 'John 14:2',
    explanation: 'Jesus promises a place in His Father\'s house.'
  },
  {
    id: 'jhn_015_02',
    collection: 'New Testament',
    book: 'John',
    chapter: 15,
    category: 'Discipleship',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What metaphor does Jesus use to describe believers\' connection to Him?',
    choices: ['Sheep', 'Branches', 'Stones', 'Servants'],
    answer: 'Branches',
    verse: 'John 15:5',
    explanation: 'Believers must remain connected to Christ to bear fruit.'
  },
  // More Acts questions
  {
    id: 'act_001_02',
    collection: 'New Testament',
    book: 'Acts',
    chapter: 1,
    category: 'Ascension',
    difficulty: 'easy',
    type: 'multiple-choice',
    question: 'What happened to Jesus at the beginning of Acts?',
    choices: ['He was baptized', 'He ascended into heaven', 'He performed a miracle', 'He preached in Jerusalem'],
    answer: 'He ascended into heaven',
    verse: 'Acts 1:9',
    explanation: 'Jesus was taken up into heaven before the disciples.'
  },
  {
    id: 'act_004_01',
    collection: 'New Testament',
    book: 'Acts',
    chapter: 4,
    category: 'Early Church',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What characterized the believers\' attitude toward possessions?',
    choices: ['Private ownership', 'Selling and sharing', 'Strict tithing', 'Government support'],
    answer: 'Selling and sharing',
    verse: 'Acts 4:34-35',
    explanation: 'Believers shared so no one was in need.'
  },
  {
    id: 'act_007_01',
    collection: 'New Testament',
    book: 'Acts',
    chapter: 7,
    category: 'Martyrdom',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Who was the first Christian martyr?',
    choices: ['James', 'Peter', 'Stephen', 'Philip'],
    answer: 'Stephen',
    verse: 'Acts 7:59-60',
    explanation: 'Stephen was stoned for his testimony about Jesus.'
  },
  {
    id: 'act_010_01',
    collection: 'New Testament',
    book: 'Acts',
    chapter: 10,
    category: 'Gentile Inclusion',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Who received the Holy Spirit while Peter was preaching?',
    choices: ['The apostles', 'Cornelius and his household', 'The Sanhedrin', 'The Samaritans'],
    answer: 'Cornelius and his household',
    verse: 'Acts 10:44',
    explanation: 'God showed that Gentiles were included in salvation.'
  },
  // More Romans questions
  {
    id: 'rom_012_01',
    collection: 'New Testament',
    book: 'Romans',
    chapter: 12,
    category: 'Christian Living',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'How are believers instructed to offer themselves to God?',
    choices: ['As sacrifices of praise', 'As living sacrifices', 'As offerings of money', 'As servants of the law'],
    answer: 'As living sacrifices',
    verse: 'Romans 12:1',
    explanation: 'Paul urges believers to dedicate their lives to God.'
  },
  // More 1 Corinthians
  {
    id: '1co_010_01',
    collection: 'New Testament',
    book: '1 Corinthians',
    chapter: 10,
    category: 'Warnings',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What does Paul warn believers to flee?',
    choices: ['Persecution', 'Idolatry', 'Suffering', 'Conflict'],
    answer: 'Idolatry',
    verse: '1 Corinthians 10:14',
    explanation: 'Paul warns against participating in idol worship.'
  },
  // More 2 Corinthians
  {
    id: '2co_012_01',
    collection: 'New Testament',
    book: '2 Corinthians',
    chapter: 12,
    category: 'Grace',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What did the Lord say was sufficient for Paul?',
    choices: ['Strength', 'Faith', 'Grace', 'Wisdom'],
    answer: 'Grace',
    verse: '2 Corinthians 12:9',
    explanation: 'God\'s grace is sufficient in weakness.'
  },
  // More Hebrews
  {
    id: 'heb_004_01',
    collection: 'New Testament',
    book: 'Hebrews',
    chapter: 4,
    category: 'Rest',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'What does the writer say remains for the people of God?',
    choices: ['A kingdom', 'A rest', 'A sacrifice', 'A covenant'],
    answer: 'A rest',
    verse: 'Hebrews 4:9',
    explanation: 'God\'s promised rest is still available.'
  },
  // More Revelation
  {
    id: 'rev_003_01',
    collection: 'New Testament',
    book: 'Revelation',
    chapter: 3,
    category: 'Letters to the Churches',
    difficulty: 'medium',
    type: 'multiple-choice',
    question: 'Which church is described as lukewarm?',
    choices: ['Ephesus', 'Smyrna', 'Laodicea', 'Pergamum'],
    answer: 'Laodicea',
    verse: 'Revelation 3:16',
    explanation: 'Laodicea is rebuked for being neither hot nor cold.'
  }
];

export interface UserStats {
  totalScore: number;
  quizzesCompleted: number;
  streak: number;
  badges: string[];
  seenQuestionIds: string[];
}
